import { initDatabase, importFromCSV } from '@/db/database'

const SEED_DATA = [
  { note: "P2-4 Discharge valves are closed", date: "2026-05-07", noteType: "Activity", object: "P2-4", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "CWTP logbook" },
  { note: "NRV is not working for P4-4", date: "2026-05-10", noteType: "Complaints", object: "P4-4", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "CWTP logbook" },
  { note: "HCl tanker is unloaded", date: "2026-05-07", noteType: "Activity", object: "HCl Bulk Storage Tank", objectGroup: "HCl Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "R5C all MC headers removed", date: "2026-05-07", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "Alkali tanker unloading is done in Old DM Plant", date: "2026-05-07", noteType: "Activity", object: "NaOH bulk Storage Tank", objectGroup: "NaOH Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "Expansion Plant DG blower fan casing prepared", date: "2026-05-07", noteType: "Activity", object: "Expansion DG Blower", objectGroup: "DG Blowers", objectType: "Blowers", source: "DM Reports WA group" },
  { note: "R5C MC headers all T pieces removed except for one", date: "2026-05-06", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R5C - 6 drums of resin (mixed with stones) is removed", date: "2026-05-06", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "H2SO4 unloading hose is made", date: "2026-05-06", noteType: "Activity", object: "H2SO4 bulk storage tank", objectGroup: "H2SO4 Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "H2SO4 line airlock is removed", date: "2026-05-06", noteType: "Activity", object: "", objectGroup: "H2SO4 Acid Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R6E - MC inlet valve (80 mm) diaphragm is changed", date: "2026-05-06", noteType: "Activity", object: "R6-E", objectGroup: "Anion Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "Airscouring line painted with red oxide", date: "2026-05-06", noteType: "Activity", object: "MB Airscouring line", objectGroup: "MB Regeneration System", objectType: "Others", source: "DM Reports WA group" },
  { note: "R5F shell leakage arrested by pasting rubber lining gum", date: "2026-05-05", noteType: "Activity", object: "R5-F", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "HCl tank outlet line common valve bonnet and diaphragm changed", date: "2026-05-05", noteType: "Activity", object: "HCl Bulk Storage Tank", objectGroup: "HCl Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "Alkali unloading hose prepared", date: "2026-05-05", noteType: "Activity", object: "", objectGroup: "NaOH Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "Alkali tanker unloading is done", date: "2026-05-05", noteType: "Activity", object: "NaOH bulk Storage Tank", objectGroup: "NaOH Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "P2-2 frame work is going on", date: "2026-05-05", noteType: "Activity", object: "P2-2", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R5E bottom dummy tightened", date: "2026-05-05", noteType: "Activity", object: "R5-E", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R7E airscouring line modification work is going on", date: "2026-05-04", noteType: "Activity", object: "R7-E", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "Alkali hose leakage is found, it is to be changed", date: "2026-05-04", noteType: "Complaints", object: "", objectGroup: "NaOH Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P8B regeneration pump oil seal leak, to be changed tomorrow", date: "2026-05-04", noteType: "Complaints", object: "P8-B", objectGroup: "DM Regeneration Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "HCl Bulk Storage tank valve leakage is arrested", date: "2026-05-04", noteType: "Activity", object: "HCl Bulk Storage Tank", objectGroup: "HCl Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "P7-A oil change is done", date: "2026-05-04", noteType: "Activity", object: "P7-A", objectGroup: "DM Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P7-D oil change is done", date: "2026-05-04", noteType: "Activity", object: "P7-D", objectGroup: "DM Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P7B greasing is done", date: "2026-05-04", noteType: "Activity", object: "P7-B", objectGroup: "DM Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P5B greasing is done", date: "2026-05-04", noteType: "Activity", object: "P5-B", objectGroup: "Clarified Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P4B greasing is done", date: "2026-05-04", noteType: "Activity", object: "P4-B", objectGroup: "Clarified Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "P7-B airscouring line new pipe preperation is almost done", date: "2026-05-03", noteType: "Activity", object: "R7-B", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "WBA Air vent valve pin refixed", date: "2026-05-03", noteType: "Activity", object: "WBA", objectGroup: "Anion Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "P8B bearing noise found due to low oil level, oil is to be refilled", date: "2026-05-03", noteType: "Complaints", object: "P8-B", objectGroup: "DM Regeneration Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "H2SO4 transfer pump P9-A basement work started", date: "2026-05-02", noteType: "Activity", object: "P9-A", objectGroup: "H2SO4 Acid Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "HCl tanker unloading is done", date: "2026-05-02", noteType: "Activity", object: "HCl Bulk Storage Tank", objectGroup: "HCl Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "Clariflocculator 3 weir area algae cleaning is done", date: "2026-05-02", noteType: "Activity", object: "Clariflocculator 3", objectGroup: "Clariflocculators", objectType: "Others", source: "DM Reports WA group" },
  { note: "R5C MC headers removing work is started", date: "2026-05-02", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R7-B airscouring line modification work started", date: "2026-05-02", noteType: "Activity", object: "R7-B", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "[Expansion] SAC-A solution tank both outlet valves diaphragms are changed", date: "2026-05-02", noteType: "Activity", object: "SAC-A", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "[Expansion] SMBS dosing line before cartridge filter inlet, leakage arrested, welding done", date: "2026-05-02", noteType: "Activity", object: "SMBS dosing line", objectGroup: "SMBS Dosing system", objectType: "Chemical Dosing Systems", source: "DM Reports WA group" },
  { note: "[Expansion] Regeneration pump P22-B coupling got damaged, so it was rectified.", date: "2026-05-02", noteType: "Activity", object: "Expansion P22-B", objectGroup: "Expansion Regeneration System", objectType: "Regeneration Systems", source: "DM Reports WA group" },
  { note: "Alum Dosing line flushing is done", date: "2026-05-08", noteType: "Activity", object: "", objectGroup: "Alum Dosing Pumps", objectType: "Chemical Dosing Systems", source: "DM Reports WA group" },
  { note: "H2SO4 tanker unloading is done", date: "2026-05-08", noteType: "Activity", object: "H2SO4 bulk storage tank", objectGroup: "H2SO4 Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "R5A all service inlet valves diaphragms are changed", date: "2026-05-08", noteType: "Activity", object: "R5-A", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R5E bottom flange leak arrested", date: "2026-05-08", noteType: "Activity", object: "R5-E", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R6A backwash outlet valve bonnet is changed", date: "2026-05-08", noteType: "Activity", object: "R6-A", objectGroup: "Anion Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R7B airscouring line changed and new pneumatic valve placed, pneumatic line connection is pending", date: "2026-05-08", noteType: "Activity", object: "R7-B", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R5C bottom pipelines removed, bottom flange 3 bolts leftover", date: "2026-05-08", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "H2SO4 pump bed concrete work done", date: "2026-05-08", noteType: "Activity", object: "P9-A", objectGroup: "H2SO4 Acid Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R5E backwash outlet valve repaired", date: "2026-05-08", noteType: "Activity", object: "R5-E", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R9B backwash outlet pipe leakage, will be attended tomorrow", date: "2026-05-08", noteType: "Complaints", object: "R9-B", objectGroup: "Softners", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "P1-6 motor side temperature was high, informed electrical", date: "2026-05-08", noteType: "Abnormality", object: "P1-6", objectGroup: "TPP Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "Expansion Plant DG Blower A casing work is done. Trail run will be taken tomorrow", date: "2026-05-08", noteType: "Activity", object: "Expansion DG Blower", objectGroup: "DG Blowers", objectType: "Others", source: "DM Reports WA group" },
  { note: "Expansion Plant Clariflocculator Bridge Drive was found to be tripped, started again and taken into service", date: "2026-05-08", noteType: "Abnormality", object: "Expansion Clariflocculator", objectGroup: "Clariflocculators", objectType: "Others", source: "DM Reports WA group" },
  { note: "In Expansion DM Plant Lye is leaking drop by drop from the middle of the heavily corroded Lye unloading line", date: "2026-05-08", noteType: "Resolved Complaint", object: "Expansion NaOH bulk storage tank", objectGroup: "NaOH Bulk Storage Tanks", objectType: "Storage Tanks", source: "" },
  { note: "In Expansion DM Plant, SAC-A acid preparation tank inlet valve handle came out. Informed mechanical, will be attended tomorrow.", date: "2026-05-09", noteType: "Resolved Complaint", object: "SAC-A", objectGroup: "Cation Regeneraton System", objectType: "Regeneration Systems", source: "" },
  { note: "R5E backwash inlet valve diaphragm is changed", date: "2026-05-10", noteType: "Activity", object: "R5-E", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "" },
  { note: "P1-2 motor side temperature was high, changed to P1-6", date: "2026-05-10", noteType: "Abnormality", object: "P1-2", objectGroup: "TPP Pumps", objectType: "Pumps", source: "" },
  { note: "P2-4 motor side temperature was high, changed to P4-4", date: "2026-05-10", noteType: "Abnormality", object: "P2-4", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "" },
  { note: "P4-D pump oil was found empty, mechanical check required.", date: "2026-05-10", noteType: "Abnormality", object: "P4-D", objectGroup: "Clarified Pumps", objectType: "Pumps", source: "" },
  { note: "Expansion Plant SAC-A acid filling valve changed. Filling done.", date: "2026-05-10", noteType: "Activity", object: "SAC-A", objectGroup: "Expansion Regeneration System", objectType: "Exchangers", source: "" },
  { note: "In expansion plant, SBA-A power water valve got jammed. It was cleared and the issue is resolved.", date: "2026-05-10", noteType: "Resolved Complaint", object: "SBA-A", objectGroup: "Expansion Regeneration System", objectType: "Exchangers", source: "" },
  { note: "P6E pump got overload tripped during running condition. ECR checked and restored. P6D was kept in service.", date: "2026-05-10", noteType: "Abnormality", object: "P6-E", objectGroup: "DG Pumps", objectType: "Pumps", source: "" },
  { note: "R5C resin removed", date: "2026-05-11", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "" },
  { note: "R5C bottom nozzle removing work is going on", date: "2026-05-12", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "" },
  { note: "R7B air scouring line instrumentation pipe changed", date: "2026-05-11", noteType: "Activity", object: "R7-B", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "" },
  { note: "R5E backwash outlet pneumatic valve is replaced with another valve", date: "2026-05-11", noteType: "Activity", object: "R5-E", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "" },
  { note: "WBA rinse valve servicing is done", date: "2026-05-11", noteType: "Activity", object: "WBA", objectGroup: "Anion Exchangers", objectType: "Exchangers", source: "" },
  { note: "P2-2 frame work is going on", date: "2026-05-11", noteType: "Activity", object: "P2-2", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "" },
  { note: "Sludge Pump servicing is done", date: "2026-05-11", noteType: "Activity", object: "Sludge Pump", objectGroup: "Sludge Pumps", objectType: "Pumps", source: "" },
  { note: "P1-6 electrical maintenance work is completed. Taken into service. Operating normally with no abnormal sounds.", date: "2026-05-11", noteType: "Activity", object: "P1-6", objectGroup: "TPP Pumps", objectType: "Pumps", source: "" },
  { note: "R7F lye preparation tank, when filled up to 75% according to gauge glass, tank is getting overflown. Gauge glass needs to be cleaned.", date: "2026-05-12", noteType: "Resolved Complaint", object: "R7-F", objectGroup: "MB Regeneration System", objectType: "Regeneration Systems", source: "" },
  { note: "P8B is given shutdown for mechanical maintenance", date: "2026-05-12", noteType: "Complaints", object: "P8-B", objectGroup: "DM Regeneration Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R7C airscouring line modification work is going on", date: "2026-05-12", noteType: "Activity", object: "R7-C", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "P2-2 bed work is going on", date: "2026-05-12", noteType: "Activity", object: "P2-2", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "H2SO4 pump bed refractory brick work 50% completed (CED)", date: "2026-05-12", noteType: "Activity", object: "P9-A", objectGroup: "H2SO4 Acid Transfer Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R7F lye level indicator inlet valve 40 dia bonnet changed", date: "2026-05-12", noteType: "Activity", object: "R7-F", objectGroup: "Mixed Bed Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "P6E pump tripped during running condition at 9:30 AM, informed electrical", date: "2026-05-13", noteType: "Abnormality", object: "P6-E", objectGroup: "DG Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "Expansion plant bridge agitator 1 towards drive side under mechanical maintenance", date: "2026-05-13", noteType: "Resolved Complaint", object: "Expansion Clariflocculator", objectGroup: "Clariflocculators", objectType: "Others", source: "" },
  { note: "RO-C is in high pH chemical cleaning", date: "2026-05-13", noteType: "Activity", object: "RO-C", objectGroup: "RO Membranes", objectType: "Membranes", source: "DM Reports WA group" },
  { note: "Expansion DM Plant polyelectrolyte pump B under electrical maintenance", date: "2026-05-13", noteType: "Resolved Complaint", object: "Expansion Polelectrolyte Pump B", objectGroup: "Polyelectrolyte Dosing Pumps", objectType: "Pumps", source: "" },
  { note: "P2-2 drilling was done by CED for frame sitting", date: "2026-05-13", noteType: "Activity", object: "P2-2", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R4B service inlet piece was changed (removed from R4C)", date: "2026-05-13", noteType: "Activity", object: "R4-B", objectGroup: "Activated Carbon Filters", objectType: "Filters", source: "DM Reports WA group" },
  { note: "R5C bottom nozzles 30 removed. All bottom caps were removed.", date: "2026-05-13", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "P2-2 frame sitting done", date: "2026-05-14", noteType: "Activity", object: "P2-2", objectGroup: "CDCP Pumps", objectType: "Pumps", source: "DM Reports WA group" },
  { note: "R5-C nozzle removing work going on", date: "2026-05-14", noteType: "Activity", object: "R5-C", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "HCl FRP tank pipe line work going on", date: "2026-05-14", noteType: "Activity", object: "Expansion HCl Bulk Storage Tank", objectGroup: "HCl Bulk Storage Tanks", objectType: "Storage Tanks", source: "DM Reports WA group" },
  { note: "R5F bed leakage arrested by applying m-seal", date: "2026-05-14", noteType: "Activity", object: "R5-F", objectGroup: "Cation Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "R6A air vent bend leakage arrested", date: "2026-05-14", noteType: "Activity", object: "R6-A", objectGroup: "Anion Exchangers", objectType: "Exchangers", source: "DM Reports WA group" },
  { note: "RO-C low pH chemical cleaning is completed. Taken into service.", date: "2026-05-14", noteType: "Activity", object: "RO-C", objectGroup: "RO Membranes", objectType: "Membranes", source: "DM Reports WA group" },
  { note: "RO-A is stopped and service inlet line is dummied", date: "2026-05-14", noteType: "Activity", object: "RO-A", objectGroup: "RO Membranes", objectType: "Membranes", source: "DM Reports WA group" },
]

export async function seedDatabase() {
  const db = await initDatabase()
  // Check if already seeded
  const result = db.exec('SELECT COUNT(*) as count FROM log_entries')
  const count = result[0]?.values[0]?.[0] as number
  if (count > 0) return // Already has data

  importFromCSV(SEED_DATA)
  console.log(`Seeded ${SEED_DATA.length} entries`)
}